[package]
name = "poncu"
version = "0.1.0"
edition = "2021"
authors = ["Sheroz Khaydarov"]
description = "ponci"
documentation = "https://docs.rs/poncu"
readme = "README.md"
repository = "https://github.com/sheroz/poncu"
license = "MIT"
