[package]
name = "ponci"
version = "0.1.0"
edition = "2021"
authors = ["Sheroz Khaydarov"]
description = "Distributed Data Storage Service"
documentation = "https://docs.rs/ponci"
readme = "README.md"
repository = "https://github.com/sheroz/ponci"
license = "MIT"
keywords = ["storage", "cache", "file-server"]
