# poncu configuration file

# server node settings
node:
  name: poncu7
  description: "Poncu server #7 at cool dedicated hardware in a great data center"
  id: poncu1@0007_cdh_gdc
  access_token: face0aa08c29eb27aa3e0ebb7fe9d9a678a9caecc1f7b886e35bc16b1c266f42
  listen_addresses: 127.0.0.1
  listen_port: 9191
  connections_max: 20
  threads_max: 4
  ram_max: 512M
  disk_max: 2G
  disk_root: "/var/poncu"

# pool of remote server nodes
remote:
  nodes: 127.0.0.1:9191

# client settings
client:
  name: test
  id: test1@file_api
  access_token: bbc5f7280aa440648d2ca6023610956da401739283ec77593492aa385f256dec

# redundancy settings
redundancy:
  # strategy: normal   - replicate item on 'redundancy_replica_min' nodes
  # strategy: maximum  - replicate item on 'redundancy_replica_max' nodes if there are enough resources 
  # strategy: paranoid - replicate item on all nodes if there are enough resources
  strategy: normal
  replica_min: 2
  replica_max: 5

## end of configuration
